### ISSUE TITLE
[Suggestion] Auto updating for self-hosted library

### ISSUE THREAD

**Issue by ecker00** [habedi/gogg#6]
As suggested on Reddit, if Gogg could be used to keep a self-hosted library (RomM) up to date. Ref: https://github.com/rommapp/romm/issues/720

I see quite a few things to tackle to fulfill such a role:
- Docker image, so it can easily run on a server alongside RomM
- Watcher mode which looks for updates once a day
- Output dir by platform, Romm expects each platform on ./win ./linux ./mac etc.
- Authentication on remote (as is would be running on a headless server)

Hypothetical how it could maybe work in the end:
```yml
services:
  romm:
    image: rommapp/romm # Bit simplified for demonstation
    volumes:
      - ./library:/romm/library
    ports:
      - 8080:8080

  gogg:
    image: habedi/gogg
    volumes:
      - ./library:/romm/library
    environment:
      - ACCESS_TOKEN=123 # Some method to obtain auth
      - PLATFORM_WIN=/library/win # Expected path for RomM
      - PLATFORM_MAC=/library/mac
      - PLATFORM_LINUX=/library/linux
    command: gogg watch --platform=all  --lang=en --threads=3 --dlcs=true --extras=false
```

**Comment by habedi** [comment]
Sounds like an interesting idea. 

Just one thing: I think the current version of Gogg supports the watching for updates operation already, which can be achieved with something like:

`gogg download --id=<game-id> --dir=<storage-dir> --resume=true --extras=false --dlcs=true`

This won't download files that have already been downloaded, only the new files like patches for Windows games and updated installers for Linux and macOS.

**Comment by lifo9** [comment]
I do it like this:

1. Log into GoG on your host system, copy the database `games.db` to your server.

2. Create Gogg Docker image and push it to some container registry ([entrypoint.sh is from here](https://github.com/habedi/gogg/blob/main/docs/examples/download_all_games.sh)):
```dockerfile
FROM debian:trixie-20250520-slim
RUN apt-get update && apt-get install -y --no-install-recommends curl unzip ca-certificates libgl1 \
&& curl -L -o /usr/local/bin/gogg.zip https://github.com/habedi/gogg/releases/download/v0.4.1-beta/gogg-linux-amd64.zip \
&& unzip /usr/local/bin/gogg.zip -d /usr/local/bin \
&& rm /usr/local/bin/gogg.zip \
&& chmod +x /usr/local/bin/gogg \
&& apt-get purge -y --auto-remove curl unzip \
&& rm -rf /var/lib/apt/lists/*
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
```

3. Create a K8S CronJob (you could also do this with docker with some tweaking):
```yaml
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: romm-gogg
  namespace: romm
  labels:
    app: romm-gogg
spec:
  schedule: "0 2 * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: romm-gogg
        spec:
          serviceAccountName: romm
          securityContext:
            runAsNonRoot: true
          containers:
          - image: gogg:latest # put the correct path to the container registry here
            imagePullPolicy: IfNotPresent
            name: romm-gogg
            command: ["/bin/bash", "-c", "HOME=/gogg /entrypoint.sh"] # Gogg database is [hardcoded](https://github.com/habedi/gogg/blob/main/db/db.go#L16) to be stored in the `$HOME` directory
            envFrom:
            - configMapRef:
                name: romm-gogg
            volumeMounts:
            - name: data
              mountPath: /gogg
              subPath: gogg
            - name: games
              mountPath: /gog_games
              subPath: roms/win
          volumes:
          - name: data
            persistentVolumeClaim:
              claimName: romm
          - name: games
            persistentVolumeClaim:
              claimName: romm-games
          restartPolicy: Never
```
